/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "background": "#fcf9f8",
        "surface": "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0edec",
        "surface-container-high": "#ebe7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-variant": "#e5e2e1",
        "primary": "#000000",
        "primary-container": "#3b3b3b",
        "primary-fixed": "#5e5e5e",
        "primary-fixed-dim": "#474747",
        "inverse-primary": "#c6c6c6",
        "secondary": "#5f5e5e",
        "secondary-container": "#d6d4d3",
        "secondary-fixed": "#c8c6c6",
        "secondary-fixed-dim": "#acabab",
        "tertiary": "#254136",
        "tertiary-container": "#5e7b6e",
        "tertiary-fixed": "#486458",
        "tertiary-fixed-dim": "#304c41",
        "outline": "#777777",
        "outline-variant": "#c6c6c6",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-background": "#1c1b1b",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#474747",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "on-primary": "#e2e2e2",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#ffffff",
        "on-primary-fixed-variant": "#e2e2e2",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#1b1c1c",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#3b3b3b",
        "on-tertiary": "#caeada",
        "on-tertiary-container": "#ffffff",
        "on-tertiary-fixed": "#ffffff",
        "on-tertiary-fixed-variant": "#caeada",
        "on-error": "#ffffff",
        "on-error-container": "#410002",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        ambient: "0px 12px 32px rgba(28, 27, 27, 0.06)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      letterSpacing: {
        editorial: "-0.02em",
      },
    },
  },
  plugins: [],
};
